version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/link_aggregator.db
      - NODE_ENV=production

volumes:
  sqlite_data: 